version: '3'
services:
  neo4j:
    restart: always
    image: neo4j:3.5
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
  app:
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=app:app
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./commentality:/app
    depends_on:
      - neo4j
    entrypoint: ["flask", "run", "--host=0.0.0.0"]
    container_name: backmentality
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/commentality.conf
      - /home/commentality/commentality-client/:/var/commentality-client/
      - /etc/letsencrypt/:/etc/certs/
      - /home/commentality/commentality-landing/:/var/commentality-landing/

volumes:
  neo4j-data:
