version: '3'
services:
  neo4j:
    restart: always
    image: neo4j:3.5
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
  app:
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=app:app
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./commentality:/app
    depends_on:
      - neo4j
    entrypoint: ["flask", "run", "--host=0.0.0.0"]

volumes:
  neo4j-data:
